dailyexpenseapp2/urls.py
from django.contrib import admin
from django.urls import path
from . import views as v

urlpatterns = [
    path('adduser',v.adduser,name='adduser'),
    path('addincome',v.addIncome,name='addincome'),
    path('addexpense',v.addExpense,name='addExpense'),
    path('incomelist',v.IncomeList,name='incomeList'),
    path('expenseList',v.expenseList,name='expenseList'),
    path('login',v.login_view,name='login'),
    path('logout',v.logout_view,name='logout'),
    path('dincome/<int:id>/',v.deleteinc,name='deleteinc'),
    path('dexpense/<int:id>/',v.deleteexp,name='deleteexp'),


  
  
]

dailyexpenseproject2/urls.py
from django.contrib import admin
from django.urls import path,include
from dailyexpenseapp2 import views as v

urlpatterns = [
    path('expm',include(('dailyexpenseapp2.urls','dailyexpenseapp2'), namespace='expm')),
    path('', v.home),
]

dailyexpenseapp2/models.py
from django.db import models
from django.contrib.auth.models import User


class UserInfo(User):
    age=models.IntegerField()
    contact=models.IntegerField()

    class Meta:
        db_table='user_info'

class Income(models.Model):
    income=models.IntegerField()
    incomeType=models.CharField(max_length=20)
    incomeDate=models.IntegerField()
    description=models.CharField(max_length=20)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

class Expense(models.Model):
    expense=models.IntegerField()
    expenseType=models.CharField(max_length=20)
    description=models.CharField(max_length=20)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

class login(models.Model):
    username=models.CharField(max_length=20)
    password=models.CharField(max_length=20)

dailyexpenseapp2/forms.py
from django import forms
from .models import UserInfo,Income,Expense,login
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserForm(UserCreationForm):
    class Meta:
        model=UserInfo
        fields=['username','first_name','last_name','age','contact','email','password1','password2']

class IncomeForm(forms.ModelForm):
    class Meta:
        model=Income
        fields='__all__'

class ExpenseForm(forms.ModelForm):
    class Meta:
        model=Expense
        fields='__all__'

class LoginForm(forms.ModelForm):
    class Meta:
        model=login
        fields='__all__'

dailyexpenseapp2/views.py
from django.shortcuts import render,HttpResponse,redirect
from .models import UserInfo,Income,Expense
from django.contrib.auth import login,logout,authenticate
from .forms import UserForm,IncomeForm,ExpenseForm,LoginForm

def home(request):
   bal=getbal(request)
   return render(request,'index.html')

def adduser(request):
   if request.method=='POST':
      f=UserForm(request.POST)
      f.save()
      return redirect('/')
   else:
      f=UserForm
      return render(request,'register.html',{'form':f})

def addIncome(request):
   if request.method=='POST':
      f=IncomeForm(request.POST)
      f.save()
      return redirect('/')
   else:
      f=IncomeForm
      return render(request,'forms.html',{'form':f})

def addExpense(request):
   if request.method=='POST':
      f=ExpenseForm(request.POST)
      f.save()
      return redirect('/')
   else:
      f=ExpenseForm
      return render(request,'forms.html',{'form':f})


def IncomeList(request):
   id=request.session.get('uid')
   f=Income.objects.filter(id=id)
   return render(request,'income_list.html',{'f':f})

def expenseList(request):
   id=request.session.get('uid')
   f=Expense.objects.filter(id=id)
   return render(request,'expense_list.html',{'f':f})


def login_view(request):
   if request.method=='POST':
      uname=request.POST.get('username')
      pword=request.POST.get('password')
      details=authenticate(request,username=uname,password=pword)
      
      if details is not None:
         request.session['uid']=details.id
         login(request, details)
         return redirect('/')
      else:
         return HttpResponse('Invalid username or password')
   else:
      f=LoginForm
      return render(request,'login.html',{'form':f})


def logout_view(request):
   logout(request)
   return redirect('/')
      
def deleteinc(request,id):
  
   del_id=Income.objects.get(id=id)
   del_id.delete()
   return redirect('/')

def deleteexp(request,id):
   del_id=Expense.objects.get(id=id)
   del_id.delete()
   return redirect('/')

def getbal(request):
   totalInc=0
   id=request.session.get('uid')
   inc=Income.objects.filter(id=id)

   for i in inc:
      totalInc+=i

   return(totalInc)


   









    

dailyexpenseapp2/templates/expense_list.html
{% extends 'sidebar.html' %}
{% block Content%}

<table border="1">
    
    <tr>
        <th>Expense</th>
        <th>Expense Type</th>
   
        <th>Description</th>
        <th>User</th>
        <th colspan="2">Action</th>


    </tr>
    {% for i in f%}
    <tr>
        <td>{{i.expense}}</td>
        <td>{{i.expenseType}}</td>
        <td>{{i.description}}</td>
        <td>{{i.user}}</td>
        <td><a href="{% url 'expm:deleteexp' i.id %}">Delete</a></td>
        <td><a href="{% url 'expm:deleteexp' i.id %}">Edit</a></td>



    </tr>
    {% endfor %}
</table>
{% endblock %}

dailyexpenseapp2/templates/forms.html
{% extends 'sidebar.html' %}
{% block Content%}
<form method="POST">
    {% csrf_token %}
    <table>
        {{form.as_table}}

    </table>
    <td>
        <tr><input type='submit'></tr>
        <tr><input type='reset'></tr>
    </td>
</form>
{%endblock%}

dailyexpenseapp2/templates/income_list.html
{% extends 'sidebar.html' %}
{% block Content%}

<table border="1">
    
    <tr>
        <th>Income</th>
        <th>IncomeType</th>
        <th>IncomeDate</th>
        <th>Description</th>
        <th>User</th>
        <th colspan="2">Action</th>


    </tr>
    {% for i in f%}
    <tr>
        <td>{{i.income}}</td>
        <td>{{i.incomeType}}</td>
        <td>{{i.incomeDate}}</td>
        <td>{{i.description}}</td>
        <td>{{i.user}}</td>
        <td><a href="{% url 'expm:deleteinc' i.id %}">Delete</a></td>
        <td><a href="{% url 'expm:deleteinc' i.id %}">Edit</a></td>



    </tr>
    {% endfor %}
</table>
{% endblock%}

dailyexpenseapp2/templates/index.html
{% extends 'sidebar.html' %}
{% block Content%}
{%if user.is_authenticated%}

<h1 style="text-align: center;">Daily Expense Management Application</h1>
<h2>Welcome, {{user.first_name}}</h2>
<h2>Your Balance is {{bal}}</h2>

{%endif%}
{%  endblock%}

dailyexpenseapp2/templates/login.html
{% extends 'sidebar.html' %}
{% block Content%}

<form method='POST'>
    {% csrf_token%}
    <table>
        {{form.as_table}}
    <tr>
        <td><input type='submit'></td>
    </tr>
    </table>
</form>
{% endblock%}

    

dailyexpenseapp2/templates/register.html
{% extends 'sidebar.html' %}
{% block Content%}

<form method='POST'>
    {% csrf_token %}
    <table>
        {{form.as_table}}
        <tr>
            <td><input type='submit'></td>
            <td><input type='reset'></td>
        </tr>
        
    </table>
</form>
{%endblock%}

dailyexpenseapp2/templates/sidebar.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: "Lato", sans-serif;
}

.sidenav {
  height: 100%;
  width: 160px;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #111;
  overflow-x: hidden;
  padding-top: 20px;
}

.sidenav a {
  padding: 6px 8px 6px 16px;
  text-decoration: none;
  font-size: 25px;
  color: #818181;
  display: block;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.main {
  margin-left: 160px; /* Same as the width of the sidenav */
  font-size: 28px; /* Increased text to enable scrolling */
  padding: 0px 10px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
</style>
</head>
<body>

<div class="sidenav">
    


    {%if user.is_authenticated%}
    <h2><a href='/'>Home</a></h2>
    <h2><a href="{% url 'expm:addincome' %}">Add Income</a></h2>
    <h2><a href="{% url 'expm:addExpense' %}">Add Expense</a></h2>
    <h2><a href="{% url 'expm:incomeList' %}">Income List</a></h2>
    <h2><a href="{% url 'expm:expenseList' %}">Expense List</a></h2>
    <h2><a href="{% url 'expm:adduser' %}">Edit Profile</a></h2>
    <h2><a href="{% url 'expm:logout' %}">logout</a></h2>
    
    
    {%else%}
    <h2><a href='/'>Home</a></h2>
    <h2><a href="{% url 'expm:adduser' %}">Register</a></h2>
    <h2><a href="{% url 'expm:adduser' %}">About Us</a></h2>
    <h2><a href="{% url 'expm:login' %}">Login</a></h2>
    
    {%endif%}
    
</div>

<div class="main">
 {% block Content%}
 {%endblock%}
</body>
</html> 